<?php
require_once 'database.php';require_once 'functions.php';session_start();require_login();$me=user();$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();$target=(int)($_POST['target']??0);
 if($target && $target!=$me['id']){
  if(isset($_POST['like'])&&!blocked_between($me['id'],$target)){$q=$db->prepare("INSERT OR IGNORE INTO likes(user_id,liked_user_id) VALUES(?,?)");$q->execute([$me['id'],$target]);}
  if(isset($_POST['block'])){$q=$db->prepare("INSERT OR IGNORE INTO blocks(user_id,blocked_id) VALUES(?,?)");$q->execute([$me['id'],$target]);$db->prepare("DELETE FROM likes WHERE (user_id=? AND liked_user_id=?) OR (user_id=? AND liked_user_id=?)")->execute([$me['id'],$target,$target,$me['id']]);$notice='That profile has been blocked.';}
  if(isset($_POST['report'])){ $reason=trim($_POST['reason']??'');$details=trim($_POST['details']??'');$allowed=['Harassment or bullying','Spam or scam','Inappropriate content','Impersonation','Other']; if(!in_array($reason,$allowed,true))$reason='Other'; $q=$db->prepare("INSERT INTO reports(reporter_id,reported_id,reason,details) VALUES(?,?,?,?)");$q->execute([$me['id'],$target,$reason,substr($details,0,2000)]);$notice='Report submitted to the moderation team.'; }
 }
}
$q=$db->prepare("SELECT * FROM users WHERE id!=? AND id NOT IN (SELECT liked_user_id FROM likes WHERE user_id=?) AND id NOT IN (SELECT blocked_id FROM blocks WHERE user_id=?) AND id NOT IN (SELECT user_id FROM blocks WHERE blocked_id=?) ORDER BY created_at DESC");$q->execute([$me['id'],$me['id'],$me['id'],$me['id']]);$people=$q->fetchAll(PDO::FETCH_ASSOC);
layout_start('Discover');echo '<h1>Discover</h1><p class="muted">Welcome, '.h($me['username']).'. Find people at your own pace.</p>'.($notice?'<p class="success notice">'.h($notice).'</p>':'').'<div class="grid">';
foreach($people as $p){$avatar=!empty($p['profile_photo'])?'<img class="avatar-image" src="'.h($p['profile_photo']).'" alt="Profile photo">':'<span>✦</span>';echo '<article class="card"><div class="avatar">'.$avatar.'</div><div class="info"><h2>'.h($p['username']).'</h2><small>'.h($p['pronouns']).'</small><p>'.h($p['about']).'</p><p class="tag">'.h($p['interests']).'</p><div class="action-row"><form method="post"><input type="hidden" name="csrf" value="'.h(csrf()).'"><input type="hidden" name="target" value="'.$p['id'].'"><button class="btn" name="like">♡ Like</button> <button class="ghost" name="block">⛔ Block</button></form><details class="report"><summary>⚑ Report</summary><form method="post" class="report-form"><input type="hidden" name="csrf" value="'.h(csrf()).'"><input type="hidden" name="target" value="'.$p['id'].'"><label>Reason<select name="reason"><option>Harassment or bullying</option><option>Spam or scam</option><option>Inappropriate content</option><option>Impersonation</option><option>Other</option></select></label><label>Details<textarea name="details" maxlength="2000" placeholder="Tell moderators what happened..."></textarea></label><button class="danger" name="report">Submit report</button></form></details></div></div></article>';}
if(!$people)echo '<p class="muted">No new profiles right now.</p>';echo '</div>';layout_end();
